### ISSUE TITLE
Build doesn't work when cross-compiling

### ISSUE THREAD

**Issue by spease** [pedrosland/mmal-sys#1]
Got the following result attempting to cross-compile under Linux:
```
cargo build --target=armv7-unknown-linux-gnueabihf                      
warning: unused manifest key: target.armv7-unknown-linux-gnueabihf.linker
   Compiling mmal-sys v0.0.0
error: failed to run custom build command for `mmal-sys v0.0.0`
process didn't exit successfully: `/home/spease/projects/carlos/trigger/target/debug/build/mmal-sys-3a70905a07de7472/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-lib=mmal_core
cargo:rustc-link-lib=mmal_util
cargo:rustc-link-lib=mmal_vc_client
cargo:rustc-link-lib=vcos
cargo:rustc-link-lib=bcm_host
cargo:rustc-link-search=native=/opt/vc/lib

--- stderr
wrapper.h:1:10: fatal error: 'interface/mmal/mmal.h' file not found
wrapper.h:1:10: fatal error: 'interface/mmal/mmal.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by pedrosland** [comment]
Thanks for checking out my library. Fixing this is was on my todo list actually.

I have set up [Cross](https://github.com/japaric/cross) for testing this. You'll also need [my config](https://github.com/pedrosland/mmal-sys/blob/master/Cross.toml).

Do you have the mmal headers on your machine already? On the RPI they're in `/opt/vc/include`.

I have added env vars `MMAL_INCLUDE_DIR` and `MMAL_LIB_DIR` so you can compile with `MMAL_INCLUDE_DIR=/path/include MMAL_LIB_DIR=/path/lib cargo build --target armv7-unknown-linux-gnueabihf` on [this branch](https://github.com/pedrosland/mmal-sys/tree/bug/1-cross-compile).

Please let me know if this works for you and I can publish a new release on crates.io.

---

On a side-note, I noticed that in your "trigger" repo, you're using python to access the camera. That's quite creative. mmal-sys is a low-level lib that provides ugly access to mmal.

I am working on a nicer library, more like Picamera. As an inexperienced Rust developer, I'm still working through some things like what the APIs should look like and it is very rough but the core functionality is there. I'll do some more work on it this weekend.

**Comment by spease** [comment]
I like this methodology for handling a wrapper for a C API:
https://docs.rs/rdkafka-sys/0.11.1-0/rdkafka_sys/

I don’t know how practical that is in this case

**Comment by pedrosland** [comment]
Thanks for the suggestions. I'm using versioning and bundling pre-generated bindings as that library does.

There have been some changes here and I hope that cross-compiling should now work. Please re-open this if you still experience difficulties.
