### ISSUE TITLE
locate_mmal_lib_dir panics if path does not exist

### ISSUE THREAD

**Issue by eberkund** [pedrosland/mmal-sys#2]
The library is supposed to support using a different path for mmal libs. So there is an environment variable to rerun if `MMAL_LIB_DIR` is changed.

    println!("cargo:rerun-if-env-changed=MMAL_LIB_DIR");

The issue is that if `cargo` decides to build this lib first, before my application build script is run then the build script will panic and stop it from proceeding.

I do something like this in my `build.rs`

    println!("cargo:rustc-env=MMAL_LIB_DIR=custom/path/to/lib");

The solution should be to issue a warning rather than panic I think. Do you agree with this solution @pedrosland?

**Comment by pedrosland** [comment]
@amanieu any input you can give is appreciated

**Comment by Amanieu** [comment]
You should probably be setting `MMAL_LIB_DIR` outside of cargo. Maybe write a small wrapper script around cargo which sets the needed environment variables?

**Comment by eberkund** [comment]
Okay, thanks.
