### ISSUE TITLE
signed/unsigned char mismatch in camera_name fmt function

### ISSUE THREAD

**Issue by a1k0n** [pedrosland/mmal-sys#5]
Hello,

thanks for making these bindings. I'm using `rustc 1.29.2 (17a9dc751 2018-10-05)` and it seems from_utf8 doesn't accept the c_char type (anymore?).

```
error[E0308]: mismatched types
   --> /Users/asloane/.cargo/registry/src/github.com-1ecc6299db9ec823/mmal-sys-0.1.0-2/src/lib.rs:299:35
    |
299 |             ::std::str::from_utf8(&self.camera_name).unwrap(),
    |                                   ^^^^^^^^^^^^^^^^^ expected slice, found array of 16 elements
    |
    = note: expected type `&[u8]`
               found type `&[i8; 16]`

```

Totally new to rust here, trying to port some of my C++ raspberry pi code. I assume we can cast this somehow.

**Comment by pedrosland** [comment]
Thanks for the report. I forgot about those display functions. I meant to remove them as they are ugly and the rascam implementation of this is better.

I don't claim to be an expert on C. Rust has the `c_char` type for interop with C. It, as the [rust docs say](https://doc.rust-lang.org/std/os/raw/type.c_char.html), can be signed or unsigned like in C. In C it seems that on x86_64, c_char is unsigned but on armv7 it is signed.

To confirm I wrote a small program to test.

Raspberry Pi 3:
``` $ cat rust-char.rs
#[test]
fn test_char() {
    let char = 1 as ::std::os::raw::c_char;
    assert!(char == 1u8);
}

$ rustup show
...
stable-armv7-unknown-linux-gnueabihf (default)
rustc 1.29.2 (17a9dc751 2018-10-05)

$ rustc --test rust-char.rs
$ echo $?
0
```

Laptop:
```
$ rustup show
...
stable-x86_64-unknown-linux-gnu (default)
rustc 1.29.2 (17a9dc751 2018-10-05)

$ rustc --test rust-char.rs
error[E0308]: mismatched types
 --> rust-char.rs:4:21
  |
4 |     assert!(char == 1u8);
  |                     ^^^ expected i8, found u8

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
```

Can you check your target when trying to compile?

I'd expect something like `armv7-unknown-linux-gnueabihf`. I can recommend [cross](https://github.com/rust-embedded/cross) for making things easy.

**Comment by a1k0n** [comment]
Ah, nicely spotted. Yes I am cross-compiling. I didn't consider that char was unsigned on the armv7 compiler. Sure enough, that error goes away when I use `cargo build --target=armv7-unknown-linux-gnueabihf`, and it wouldn't have linked with the wrong target set anyway.

Thanks for the response.

**Comment by pedrosland** [comment]
You're welcome. Have fun with your project and please let me know if you encounter any more problems.
