### ISSUE TITLE
Compilation is failing

### ISSUE THREAD

**Issue by valmirjunior0088** [pedrosland/mmal-sys#8]
Compilation fails with the following message:

```
error[E0308]: mismatched types
   --> <redacted>/.cargo/registry/src/github.com-1ecc6299db9ec823/mmal-sys-0.1.0-2/src/lib.rs:290:35
    |
290 |             ::std::str::from_utf8(&self.camera_name).unwrap(),
    |                                   ^^^^^^^^^^^^^^^^^ expected slice, found array of 16 elements
    |
    = note: expected type `&[u8]`
               found type `&[i8; 16]`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `mmal-sys`.

To learn more, run the command again with --verbose.
```

How can we fix this?

**Comment by valmirjunior0088** [comment]
Currently I've simply removed the `fmt::Display` implementations and it works.

**Comment by pedrosland** [comment]
Thanks for the bug report. That sounds good for now. I'll look into this soon.

**Comment by pedrosland** [comment]
It is great that you're looking at my libraries and interested in developing for the Pi!

I can reproduce that error if I try to compile on my laptop without specifying a target (which defaults to x86_64 for me).
My Pi isn't with me right now so I can't check what happens there.

* Are you running cargo build on your Raspberry Pi?
* Are you specifying a target when you build?

**Comment by valmirjunior0088** [comment]
I was forgetting to specify the target. It works now. Sorry for the inconvenience.

**Comment by pedrosland** [comment]
Excellent. Thanks for closing this issue.
